base_url = "https://onlyduyy.github.io/"
title = "duykhanh471"
description = "Người lười học chăm"

compile_sass = true
minify_html = true
build_search_index = false
taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true

[extra]
author = "Khanh Duy"

[[extra.menu]]
name = "Archive"
url = "/"

[[extra.menu]]
name = "Tags"
url = "tags"
